networks:
  nginx:
  api:
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "1935:1935"
    volumes:
      - "./tmp:/tmp/hls"
    networks:
      - nginx
      - api
  api:
    build: ./api
    ports:
      - "3000:3000"
    networks:
      - nginx
      - api
    depends_on:
      - nginx
